# Generated by Django 5.0.3 on 2024-06-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnASolver', '0003_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Insert topics which are related to this question.', max_length=200, unique=True),
        ),
    ]
