# Generated by Django 5.0.3 on 2024-06-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnASolver', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('s', 'Solved'), ('u', 'Unsolved')], default='u', max_length=10),
        ),
    ]
