# Generated by Django 5.0.3 on 2024-07-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnASolver', '0005_alter_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
